### ISSUE TITLE
blogURI issue with single post in menu

### ISSUE THREAD

**Issue by scottopolis** [staticfuse/gatsby-theme-publisher#27]
Problem: Adding a single post to the menu when blogURI is set returns a 404.

1. Create a WP menu and add a single post to it, like "Hello World."
2. In the theme, set blogURI to any value, like "/blog"
3. In the theme, click the menu item "Hello World," it gives an error.

The problem is that the menu link does not add the blogURI to the "Hello World" item path.

**Comment by justinwhall** [comment]
Interesting. Looks like it should [here](https://github.com/staticfuse/gatsby-theme-publisher/blob/master/gatsby-theme-publisher/create/createPosts.js#L209). So are you saying in your case if you set the blogURI to "/blog" the hello world posts lives here:

`https://mydomain.com/hello-world/` 

instead of

`https://mydomain.com/blog/hello-world/` 

And the menu links to `https://mydomain.com/hello-world/`

**Comment by scottopolis** [comment]
The post lives at /blog/hello-world, but the menu links to /hello-world. Maybe we should generate pages based on the WP slug, and not use blogURI in the paths at all?

Thanks,

Scott Bolinger
